spring.application.name=upi

server.port=9090
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=030801
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.properties.hibernate.default_schema=fintech_core
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.flyway.baseline-on-migrate=true
eureka.client.enabled=false
spring.autoconfigure.exclude=org.springframework.modulith.events.jdbc.JdbcEventPublicationAutoConfiguration

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.bootstrap-servers=127.0.0.1:9092